import {
  Donation,
  ImpactStats,
  NotificationItem,
  PickupMission,
  ReceiverNGO,
  User,
  Volunteer
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-donor-1',
    name: 'Maya Lin (Green Leaf)',
    email: 'donor@sharebite.demo',
    role: 'DONOR',
    phone: '+91 98765 43210',
    area: 'Nizamabad',
    location: '742 Evergreen Terrace, Downtown Nizamabad',
    address: '742 Evergreen Terrace, Downtown Nizamabad',
    latitude: 18.6725,
    longitude: 78.0941,
    organizationName: 'Green Leaf Restaurant & Catering',
    contactPerson: 'Chef Maya Lin',
    description: 'Farm-to-table culinary restaurant committed to zero food waste in commercial kitchens.',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'user-ngo-1',
    name: 'Sarah Jenkins',
    email: 'ngo@sharebite.demo',
    role: 'NGO',
    phone: '+91 98765 43220',
    area: 'Nizamabad',
    location: '104 Hope Avenue, Gandhi Chowk, Nizamabad',
    address: '104 Hope Avenue, Gandhi Chowk, Nizamabad',
    latitude: 18.6740,
    longitude: 78.0960,
    organizationName: 'Hope Foundation Outreach',
    contactPerson: 'Sarah Jenkins (Director)',
    website: 'https://hopeoutreach.example.org',
    description: 'Community kitchen and shelter providing warm daily meals for unhoused families and seniors.',
    capacity: 60,
    demandLevel: 'HIGH',
    serviceArea: 'Nizamabad & Eastside Corridor',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'user-volunteer-1',
    name: 'Ravi Kumar',
    email: 'collector@sharebite.demo',
    role: 'VOLUNTEER',
    phone: '+91 98765 43230',
    area: 'Nizamabad',
    location: 'Tilak Road, Nizamabad',
    address: 'Tilak Road, Nizamabad',
    latitude: 18.6710,
    longitude: 78.0920,
    vehicleType: 'Bike',
    availability: 'AVAILABLE',
    description: 'Rapid food rescue courier on bicycle across Nizamabad central.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'user-volunteer-2',
    name: 'Arjun Patel',
    email: 'volunteer@sharebite.demo',
    role: 'VOLUNTEER',
    phone: '+91 98765 43231',
    area: 'Nizamabad',
    location: 'Khaleelwadi, Nizamabad',
    address: 'Khaleelwadi, Nizamabad',
    latitude: 18.6730,
    longitude: 78.0950,
    vehicleType: 'Scooter',
    availability: 'AVAILABLE',
    description: 'Eco-courier dedicated to rapid food recovery across Nizamabad.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'user-admin-1',
    name: 'David Kim',
    email: 'admin@sharebite.demo',
    role: 'ADMIN',
    phone: '+91 98765 43240',
    area: 'Nizamabad',
    location: 'ShareBite Operations Hub, Nizamabad',
    organizationName: 'ShareBite Operations Hub',
    description: 'Platform Coordinator & Community Admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'
  }
];

export const INITIAL_NGOS: ReceiverNGO[] = [
  {
    id: 'ngo-1',
    name: 'Hope Foundation',
    contactPerson: 'Sarah Jenkins',
    email: 'sarah@hopeoutreach.demo',
    phone: '+91 98765 43220',
    area: 'Nizamabad',
    location: '104 Hope Avenue, Gandhi Chowk, Nizamabad',
    address: '104 Hope Avenue, Gandhi Chowk, Nizamabad',
    latitude: 18.6740,
    longitude: 78.0960,
    serviceArea: 'Nizamabad (5km radius)',
    capacity: 60,
    currentDemand: 'HIGH',
    acceptedCategories: ['Cooked Meals', 'Fresh Produce', 'Bakery & Bread', 'Dairy & Grocery'],
    operatingHours: '08:00 - 21:00 Daily',
    website: 'https://hopefoundation.demo',
    description: 'Nonprofit serving daily meal distributions to over 150 community members in Nizamabad.'
  },
  {
    id: 'ngo-2',
    name: 'Community Care Center',
    contactPerson: 'Marcus Hayes',
    email: 'marcus@communitycare.demo',
    phone: '+91 98765 43221',
    area: 'Nizamabad',
    location: '520 Subhash Nagar, Nizamabad',
    address: '520 Subhash Nagar, Nizamabad',
    latitude: 18.6820,
    longitude: 78.1010,
    serviceArea: 'Subhash Nagar & Central Nizamabad',
    capacity: 40,
    currentDemand: 'MEDIUM',
    acceptedCategories: ['Cooked Meals', 'Packaged Goods', 'Fresh Produce', 'Bakery & Bread'],
    operatingHours: '07:30 - 19:30 Daily',
    website: 'https://communitycare.demo',
    description: 'Day shelter and family pantry helping children and families access wholesome food in Nizamabad.'
  },
  {
    id: 'ngo-3',
    name: 'Helping Hands Shelter',
    contactPerson: 'Elena Rodriguez',
    email: 'elena@helpinghands.demo',
    phone: '+91 98765 43222',
    area: 'Armoor',
    location: '89 Station Road, Armoor',
    address: '89 Station Road, Armoor',
    latitude: 18.7900,
    longitude: 78.2900,
    serviceArea: 'Armoor & Highway Corridor',
    capacity: 30,
    currentDemand: 'HIGH',
    acceptedCategories: ['Cooked Meals', 'Dairy & Grocery', 'Bakery & Bread', 'Packaged Goods'],
    operatingHours: '09:00 - 22:00 Daily',
    website: 'https://helpinghands.demo',
    description: 'Emergency community nutrition network in Armoor specializing in ready-to-eat cooked batch distributions.'
  },
  {
    id: 'ngo-4',
    name: 'Urban Breadline Collective',
    contactPerson: 'David Chen',
    email: 'david@urbanbreadline.demo',
    phone: '+91 98765 43223',
    area: 'Bodhan',
    location: '312 R.K. Colony, Bodhan',
    address: '312 R.K. Colony, Bodhan',
    latitude: 18.6600,
    longitude: 77.8800,
    serviceArea: 'Bodhan & Sugar Belt',
    capacity: 50,
    currentDemand: 'HIGH',
    acceptedCategories: ['Bakery & Bread', 'Fresh Produce', 'Packaged Goods', 'Beverages'],
    operatingHours: '06:30 - 18:00 Mon-Sat',
    website: 'https://urbanbreadline.demo',
    description: 'Dedicated bread and shelf-stable dry goods redistribution in Bodhan.'
  },
  {
    id: 'ngo-5',
    name: 'Hyderabad Relief Kitchen',
    contactPerson: 'Kiran Reddy',
    email: 'kiran@hydrelief.demo',
    phone: '+91 98765 43224',
    area: 'Hyderabad',
    location: '12 Banjara Hills, Hyderabad',
    address: '12 Banjara Hills, Hyderabad',
    latitude: 17.4150,
    longitude: 78.4480,
    serviceArea: 'Hyderabad Metro (10km radius)',
    capacity: 90,
    currentDemand: 'CRITICAL',
    acceptedCategories: ['Cooked Meals', 'Fresh Produce', 'Bakery & Bread', 'Dairy & Grocery', 'Packaged Goods'],
    operatingHours: '07:00 - 23:00 Daily',
    website: 'https://hydrelief.demo',
    description: 'High-capacity crisis kitchen supporting shelters and hospitals across Hyderabad.'
  }
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-ravi',
    name: 'Ravi Kumar',
    nickname: 'Ravi',
    email: 'collector@sharebite.demo',
    phone: '+91 98765 43230',
    area: 'Nizamabad',
    location: 'Tilak Road, Nizamabad',
    address: 'Tilak Road, Nizamabad',
    availability: 'AVAILABLE',
    vehicleType: 'Bike',
    totalMissionsCompleted: 98,
    rating: 4.96,
    latitude: 18.6710,
    longitude: 78.0920,
    activeMissionsCount: 0
  },
  {
    id: 'vol-1',
    name: 'Arjun Patel',
    nickname: 'Arjun',
    email: 'volunteer@sharebite.demo',
    phone: '+91 98765 43231',
    area: 'Nizamabad',
    location: 'Khaleelwadi, Nizamabad',
    address: 'Khaleelwadi, Nizamabad',
    availability: 'AVAILABLE',
    vehicleType: 'Scooter',
    totalMissionsCompleted: 142,
    rating: 4.95,
    latitude: 18.6730,
    longitude: 78.0950,
    activeMissionsCount: 1
  },
  {
    id: 'vol-priya',
    name: 'Priya Sharma',
    nickname: 'Priya',
    email: 'priya@sharebite.demo',
    phone: '+91 98765 43232',
    area: 'Armoor',
    location: 'Market Road, Armoor',
    address: 'Market Road, Armoor',
    availability: 'AVAILABLE',
    vehicleType: 'Van',
    totalMissionsCompleted: 76,
    rating: 4.92,
    latitude: 18.7890,
    longitude: 78.2910,
    activeMissionsCount: 0
  },
  {
    id: 'vol-vikram',
    name: 'Vikram Rao',
    nickname: 'Vikram',
    email: 'vikram@sharebite.demo',
    phone: '+91 98765 43233',
    area: 'Hyderabad',
    location: 'Madhapur, Hyderabad',
    address: 'Madhapur, Hyderabad',
    availability: 'AVAILABLE',
    vehicleType: 'Bike',
    totalMissionsCompleted: 110,
    rating: 4.94,
    latitude: 17.4480,
    longitude: 78.3900,
    activeMissionsCount: 0
  }
];

export const INITIAL_DONATIONS: Donation[] = [
  {
    id: 'don-demo-pasta',
    donorId: 'user-donor-1',
    donorName: 'Green Leaf Restaurant',
    donorEmail: 'donor@sharebite.demo',
    donorPhone: '+91 98765 43210',
    foodName: 'Nutritious Warm Pasta & Rice Grain Bowls',
    category: 'Cooked Meals',
    description: 'Freshly prepared vegetarian pasta primavera and organic brown rice grain bowls with steamed seasonal vegetables and tomato basil sauce.',
    quantity: 120,
    unit: 'meals',
    servings: 120,
    foodType: 'Cooked',
    preparationDateTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    availableFrom: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    bestBefore: new Date(Date.now() + 52 * 60 * 1000).toISOString(),
    storageCondition: 'Hot',
    packaging: 'Individual containers',
    pickupLocation: '742 Evergreen Terrace, Downtown Nizamabad',
    area: 'Nizamabad',
    latitude: 18.6725,
    longitude: 78.0941,
    allergens: ['Gluten', 'Soy'],
    safetyChecklist: {
      isSafeForConsumption: true,
      isHygienicallyPrepared: true,
      isPackagingSecure: true,
      isAllergenInfoProvided: true,
      isPickupWindowAccurate: true
    },
    priorityScore: 94,
    urgencyLevel: 'CRITICAL',
    priorityReason: 'High urgency because only 52 minutes remain until expiry and this batch contains 120 perishable cooked servings requiring hot transport.',
    status: 'MATCHING',
    allocations: [
      {
        receiverId: 'ngo-1',
        receiverName: 'Hope Foundation',
        servingsAllocated: 60,
        status: 'PENDING',
        distanceKm: 0.3,
        contactPhone: '+91 98765 43220',
        address: '104 Hope Avenue, Gandhi Chowk, Nizamabad'
      },
      {
        receiverId: 'ngo-2',
        receiverName: 'Community Care Center',
        servingsAllocated: 40,
        status: 'PENDING',
        distanceKm: 1.6,
        contactPhone: '+91 98765 43221',
        address: '520 Subhash Nagar, Nizamabad'
      },
      {
        receiverId: 'ngo-3',
        receiverName: 'Helping Hands Shelter',
        servingsAllocated: 20,
        status: 'PENDING',
        distanceKm: 24.2,
        contactPhone: '+91 98765 43222',
        address: '89 Station Road, Armoor'
      }
    ],
    totalAllocated: 120,
    isRescueMode: true,
    estimatedWindowMinutes: 52,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'don-2',
    donorId: 'user-donor-artisan',
    donorName: 'Golden Crust Artisan Bakery',
    donorEmail: 'baker@goldencrust.demo',
    donorPhone: '+1 (555) 432-1098',
    foodName: 'Artisan Sourdough Loaves & Croissants',
    category: 'Bakery & Bread',
    description: 'Assorted handcrafted sourdough loaves, brioche buns, and butter croissants baked this morning.',
    quantity: 45,
    unit: 'loaves & packs',
    servings: 90,
    foodType: 'Bakery',
    preparationDateTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    availableFrom: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    bestBefore: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    storageCondition: 'Room temperature',
    packaging: 'Sealed packages',
    pickupLocation: '188 Baker Street, Marina District',
    latitude: 37.8010,
    longitude: -122.4350,
    allergens: ['Gluten', 'Dairy'],
    safetyChecklist: {
      isSafeForConsumption: true,
      isHygienicallyPrepared: true,
      isPackagingSecure: true,
      isAllergenInfoProvided: true,
      isPickupWindowAccurate: true
    },
    priorityScore: 68,
    urgencyLevel: 'HIGH',
    priorityReason: 'Elevated priority: fresh bakery items with 6 hours shelf-life before texture quality degrades.',
    status: 'POSTED',
    allocations: [],
    totalAllocated: 0,
    isRescueMode: false,
    estimatedWindowMinutes: 360,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'don-3',
    donorId: 'user-donor-market',
    donorName: 'Valley Organic Grocers',
    donorEmail: 'manager@valleyorganic.demo',
    donorPhone: '+1 (555) 765-4321',
    foodName: 'Fresh Organic Produce Crates (Apples, Greens & Carrots)',
    category: 'Fresh Produce',
    description: 'Crisp organic Honeycrisp apples, baby spinach cartons, Dutch carrots, and bell peppers in ventilated wooden crates.',
    quantity: 80,
    unit: 'kg',
    servings: 160,
    foodType: 'Fresh Produce',
    preparationDateTime: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    availableFrom: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    bestBefore: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    storageCondition: 'Refrigerated',
    packaging: 'Cartons & Boxes',
    pickupLocation: '920 Market Street, Mid-Market',
    latitude: 37.7815,
    longitude: -122.4110,
    allergens: [],
    safetyChecklist: {
      isSafeForConsumption: true,
      isHygienicallyPrepared: true,
      isPackagingSecure: true,
      isAllergenInfoProvided: true,
      isPickupWindowAccurate: true
    },
    priorityScore: 54,
    urgencyLevel: 'MEDIUM',
    priorityReason: 'Moderate priority: fresh cold storage produce with a healthy 18-hour redistribution window.',
    status: 'ACCEPTED',
    allocations: [
      {
        receiverId: 'ngo-4',
        receiverName: 'Urban Breadline Collective',
        servingsAllocated: 160,
        status: 'ACCEPTED',
        distanceKm: 1.8,
        contactPhone: '+1 (555) 789-0123',
        address: '312 Pine Street'
      }
    ],
    totalAllocated: 160,
    isRescueMode: false,
    estimatedWindowMinutes: 1080,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&auto=format&fit=crop&q=80'
  }
];

export const INITIAL_MISSIONS: PickupMission[] = [
  {
    id: 'mission-demo-pasta',
    donationId: 'don-demo-pasta',
    foodName: 'Nutritious Warm Pasta & Rice Grain Bowls',
    servings: 120,
    donorName: 'Green Leaf Restaurant',
    donorAddress: '742 Evergreen Terrace, Downtown Metro',
    donorPhone: '+1 (555) 234-5678',
    donorCoordinates: { lat: 37.7749, lng: -122.4194 },
    receiverId: 'ngo-1',
    receiverName: 'Hope Foundation Outreach (+ 2 partners)',
    receiverAddress: '104 Hope Avenue, Eastside',
    receiverPhone: '+1 (555) 890-1234',
    receiverCoordinates: { lat: 37.7833, lng: -122.4167 },
    volunteerId: 'vol-1',
    volunteerName: 'Arjun Patel',
    volunteerPhone: '+1 (555) 456-7890',
    stage: 'VOLUNTEER_ASSIGNED',
    distanceKm: 2.4,
    etaMinutes: 14,
    pickupTimeScheduled: 'Within 20 minutes',
    notes: 'Hot insulated carrying boxes required. 120 meal containers packaged in 4 thermal crates.'
  },
  {
    id: 'mission-completed-bakery',
    donationId: 'don-completed-past',
    foodName: 'Gourmet Sandwiches & Seasonal Salads',
    servings: 75,
    donorName: 'Civic Center Bistro',
    donorAddress: '110 Van Ness Avenue',
    donorPhone: '+1 (555) 333-2222',
    donorCoordinates: { lat: 37.7765, lng: -122.4190 },
    receiverId: 'ngo-2',
    receiverName: 'Community Care Center',
    receiverAddress: '520 4th Street',
    receiverPhone: '+1 (555) 345-6789',
    receiverCoordinates: { lat: 37.7795, lng: -122.4082 },
    volunteerId: 'vol-2',
    volunteerName: 'Elena Rostova',
    volunteerPhone: '+1 (555) 234-8765',
    stage: 'RESCUED_COMPLETED',
    distanceKm: 3.1,
    etaMinutes: 0,
    conditionVerification: {
      foodServings: 75,
      condition: 'Good',
      packaging: 'Secure',
      verifiedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString()
    },
    startedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    inTransitAt: new Date(Date.now() - 3.4 * 60 * 60 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 3.1 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 3.0 * 60 * 60 * 1000).toISOString()
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    recipientRole: 'ALL',
    title: '⚡ Rescue Mode Activated',
    message: 'Green Leaf Restaurant posted 120 warm pasta meals expiring in 52 mins (Priority 94/100).',
    type: 'urgent',
    timestamp: '5 mins ago',
    isRead: false,
    actionUrl: '/listings'
  },
  {
    id: 'notif-2',
    recipientRole: 'DONOR',
    title: 'Smart Matching Calculated',
    message: 'Your donation of 120 meals was matched across Hope Foundation, Community Care, and Helping Hands (100% matched).',
    type: 'success',
    timestamp: '12 mins ago',
    isRead: false,
    actionUrl: '/donor/dashboard'
  },
  {
    id: 'notif-3',
    recipientRole: 'NGO',
    title: 'New Food Match Recommendation',
    message: 'Hope Foundation matched for 60 servings of Warm Pasta & Rice Grain Bowls (92% compatibility).',
    type: 'info',
    timestamp: '18 mins ago',
    isRead: false,
    actionUrl: '/ngo/dashboard'
  },
  {
    id: 'notif-4',
    recipientRole: 'VOLUNTEER',
    title: 'New Mission Available',
    message: 'Rapid pickup mission available: Green Leaf Restaurant to Hope Foundation (2.4 km).',
    type: 'mission',
    timestamp: '22 mins ago',
    isRead: true,
    actionUrl: '/volunteer/dashboard'
  }
];

export const INITIAL_IMPACT_STATS: ImpactStats = {
  mealsDonated: 1540,
  mealsRescued: 1280,
  donationsCompleted: 42,
  foodWasteDivertedKg: 940,
  co2AvoidedKg: 2350,
  activeDonors: 48,
  ngosSupported: 26,
  volunteerMissions: 84
};
